PAPP-35777: passing security scans for community and developer supported apps (#230)
* PAPP-35777: passing seccurity scans for community and developer supported apps

* PAPP-35777: making it work for forked repos

diff --git a/.github/actions/security-scans/action.yml b/.github/actions/security-scans/action.yml
--- a/.github/actions/security-scans/action.yml
+++ b/.github/actions/security-scans/action.yml
@@ -14,10 +14,21 @@ runs:
 
     - name: Run Security Scans
       run: |
-        set -e
+        app_json=$(find . -maxdepth 1 -name '*.json' ! -name '*.postman_collection.json')
+        publisher=$(jq -r '.publisher' "$app_json")
+        is_splunk_supported=false
+        if [[ "$publisher" == "Splunk" ]]; then
+          set -e
+          is_splunk_supported=true
+        else
+          echo "Security scans will not fail for community or developer supported apps. The SOAR team will handle the results"
+          set +e
+        fi
+
         python ${{ github.action_path }}/run_gitlab_pipeline.py 'GitHub Requirements' ${{ inputs.github-requirements-branch }} -t 600 -v "{
-          \"APP_REPO_NAME\":\"${{ github.event.repository.name }}\",
-          \"APP_REPO_BRANCH\":\"${{ github.head_ref }}\",
-          \"APP_REPO_OWNER\":\"${{ github.repository_owner }}\"
+          \"APP_REPO_NAME\":\"${{ github.event.pull_request.head.repo.name }}\",
+          \"APP_REPO_BRANCH\":\"${{ github.event.pull_request.head.ref }}\",
+          \"APP_REPO_OWNER\":\"${{ github.event.pull_request.head.repo.owner.login }}\",
+          \"SPLUNK_SUPPORTED\":\"$is_splunk_supported\"
         }"
       shell: bash
