PAPP-35404: Build app job without the need for s3 and integration tests (#158)
* PAPP-35401 Build App with minimal importing

* PAPP-35401 newlines

* PAPP-35401 update action

* PAPP-35401 specify branch for testing purposes

* PAPP-35401 add shell back

* PAPP-35401 Check out actions repo in build-app action to run python script

* PAPP-35401 Test github.action_path

* PAPP-35401 add requirements.txt local to build_app

* PAPP-35401 add shell

* PAPP-35401 addl requirements

* PAPP-35401 addl requirements

* PAPP-35401 add params

* PAPP-35401 more echos

* PAPP-35401 update branch params

* PAPP-35401 reorder params

* PAPP-35401 update ref

* PAPP-35401 use repo name without owner

* PAPP-35401 remove prints

* not uploading tar file to s3

* adding integration tests action

* PAPP-35404: addressing comments

* PAPP-35404: adding a pre commit file

* PAPP-35403: Sanity tests job (#159)

* PAPP-35403: adding sanity test action

* trigger pipeline

* PAPP-35403: changing fips check because it only affects current phantom version

* PAPP-35403: using seperate job to output variables

* PAPP-35403: moving jq stuff out of integration tests

* PAPP-35403: addressing code review comments

* PAPP-35403: testing to make sure everything works after merge

* PAPP-35404: testing entire flow

* PAPP-35404: changing pre commit hooks

---------

Co-authored-by: mnordby-splunk <mnordby@splunk.com>

diff --git a/.github/actions/integration-tests/action.yml b/.github/actions/integration-tests/action.yml
--- a/.github/actions/integration-tests/action.yml
+++ b/.github/actions/integration-tests/action.yml
@@ -1,9 +1,58 @@
 name: "Integration Tests"
-description: "Runs integration tests on the app"
+description: "Runs integration tests on the pull request"
+inputs:
+  fips_compliant:
+    description: "Is the connector fips compliant"
+    required: true
+    default: "false"
+  publisher:
+    description: "Who is the connectors publisher"
+    required: true
+  app_repo:
+    description: "Connector repo being tested"
+    required: true
 runs:
   using: "composite"
   steps:
-    - name: Run Integration Tests
-      run: |
-        echo "Running integration tests"
+    - name: Setup app in SOAR instance
       shell: bash
+      run: |
+        if [[ ${{ inputs.fips_compliant }} == "true" ]]; then
+          echo "Detected FIPS Compliant Connector"
+          export PHANTOM_INSTANCE_IP=$PHANTOM_INSTANCE_IP_FIPS
+        fi
+        echo PHANTOM_URL="https://$PHANTOM_INSTANCE_IP" >> $GITHUB_ENV
+        python ${{ github.action_path }}/../utils/app_rest_installer.py ${{ inputs.app_repo }}.tgz "$PHANTOM_INSTANCE_IP" $PHANTOM_USERNAME $PHANTOM_PASSWORD
+        if [[ "${{ inputs.app_repo }}" == *"aws"* ]]; then
+          python ${{ github.action_path }}/../utils/app_rest_installer.py ${{ inputs.app_repo }}.tgz "$AWS_PHANTOM_INSTANCE_CURRENT_VERSION_IP" $AWS_PHANTOM_USERNAME $AWS_PHANTOM_PASSWORD
+          python ${{ github.action_path }}/../utils/app_rest_installer.py ${{ inputs.app_repo }}.tgz "$AWS_PHANTOM_INSTANCE_PREVIOUS_VERSION_IP" $AWS_PHANTOM_USERNAME $AWS_PHANTOM_PASSWORD
+        fi
+    - name: Clone necessary repositories
+      shell: bash
+      run: |
+        cd ..
+        git clone https://oauth2:$GITLAB_API_TOKEN@cd.splunkdev.com/phantom-apps/app-tests.git
+    - name: Run app tests
+      env:
+        APP_TESTS_BRANCH: ${{ github.head_ref || github.ref_name }}
+      shell: bash
+      run: |
+        cd ../app-tests
+        if ! git checkout origin/$APP_TESTS_BRANCH &> /dev/null; then
+          echo "Could not find app-tests branch $APP_TESTS_BRANCH, defaulting to next."
+          git checkout next
+        fi
+        if ! vault login -method=aws role=$VAULT_ROLE &> /dev/null; then
+          echo "Failed to authenticate with Vault!"
+          exit 1
+        fi
+        if [[ -d suite/apps/"${{ inputs.app_repo }}" ]]; then
+          pytest suite/apps/"${{ inputs.app_repo }}" --color=yes --reruns=$NUM_TEST_RETRIES
+        elif [[ ${{ inputs.publisher }} == "Splunk" ]]; then
+          echo "ERROR - expected to find test suite for Splunk supported app ${{ inputs.app_repo }}"
+          exit 1
+        fi
+    - name: Clean Up
+      shell: bash
+      if: always()
+      run: vault token revoke -self || exit 0
